services:
  db:
    image: mariadb:10.11
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
      - "33060:33060"

  wordpress:
    image: wordpress:6.4-php8.2-apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "a2enmod rewrite && apache2-foreground"

volumes:
  wp_db_data: